# Generated by Django 4.0.1 on 2023-12-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('fathermobile', models.BigIntegerField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('idproof', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemgroup', models.CharField(max_length=100)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemgroup', models.CharField(max_length=50)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loandate', models.CharField(max_length=50)),
                ('customername', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('qty', models.CharField(max_length=40)),
                ('grossweight', models.CharField(max_length=40)),
                ('netweight', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=100)),
                ('loanamount', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=40)),
                ('advancepaid', models.CharField(max_length=40)),
                ('processingfees', models.CharField(max_length=40)),
                ('installments', models.CharField(max_length=40)),
                ('netpayable', models.CharField(max_length=100)),
                ('maturitydate', models.CharField(max_length=40)),
                ('paymentmode', models.CharField(max_length=40)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.CharField(max_length=500)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loannumber', models.CharField(max_length=40)),
                ('customername', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('intereststartdate', models.CharField(max_length=40)),
                ('interestcoveredtill', models.CharField(max_length=40)),
                ('monthsremaining', models.CharField(max_length=30)),
                ('totalinterestamount', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='loanitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemgroup', models.CharField(max_length=40)),
                ('itemname', models.CharField(max_length=40)),
                ('qty', models.CharField(max_length=40)),
                ('grossweight', models.CharField(max_length=40)),
                ('netweight', models.CharField(max_length=40)),
                ('purity', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=40)),
                ('loanid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.loan')),
            ],
        ),
        migrations.CreateModel(
            name='adminprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.adminlogin')),
            ],
        ),
    ]
